name: Build and test with Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24, 23, 22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy_to_render:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.API_KEY }}
          wait_deploy: true
          ref: 'v1.0.0'


    # С примера от упражнението

    # deploy_to_render:
    #   needs: build_test
    #   runs-on: ubuntu-latest
    # steps:
    #   - name: Deploy to production
    #     uses: johnbeynon/render-deploy-action@v0.0.8
    #     with:
    #       service-id: ${{ secrets.SERVICE_ID }}
    #       api-key: ${{ secrets.API_KEY }}
    #       wait-for-success: true